(function () {
  // Generated by tools/encrypt-vault.js — safe to be public, useless without the passphrase.
  const VAULT_SALT_B64 = "E827ZT/4L6nFL7ovZhpYNA==";
  const VAULT_IV_B64 = "n+VL4VvmV071WhRC9mDaWA==";
  const VAULT_CIPHERTEXT_B64 = "hOFgxH0PMdlH57c4AJeFFsQVgPQmq3K+S0mYjItliXxcoR4Gd4sY";
  const PBKDF2_ITERATIONS = 100000;

  const KONAMI_SEQUENCE = [
    "ArrowUp", "ArrowUp", "ArrowDown", "ArrowDown",
    "ArrowLeft", "ArrowRight", "ArrowLeft", "ArrowRight",
    "b", "a", "b", "a",
  ];

  function base64ToBytes(b64) {
    return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  }

  async function deriveKey(passphrase, salt) {
    const keyMaterial = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(passphrase),
      "PBKDF2",
      false,
      ["deriveKey"]
    );
    return crypto.subtle.deriveKey(
      { name: "PBKDF2", salt, iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
      keyMaterial,
      { name: "AES-CTR", length: 256 },
      false,
      ["decrypt"]
    );
  }

  async function decryptVault(passphrase) {
    const salt = base64ToBytes(VAULT_SALT_B64);
    const counter = base64ToBytes(VAULT_IV_B64);
    const ciphertext = base64ToBytes(VAULT_CIPHERTEXT_B64);
    const key = await deriveKey(passphrase, salt);
    const plainBuf = await crypto.subtle.decrypt(
      { name: "AES-CTR", counter, length: 64 },
      key,
      ciphertext
    );
    return new TextDecoder().decode(plainBuf);
  }

  const modal = document.getElementById("vault-modal");
  const cipherDisplay = document.getElementById("vault-cipher");
  const passInput = document.getElementById("vault-pass");
  const decryptBtn = document.getElementById("vault-decrypt-btn");
  const resultDisplay = document.getElementById("vault-result");
  const closeBtn = document.getElementById("vault-close-btn");

  function openModal() {
    cipherDisplay.textContent = VAULT_CIPHERTEXT_B64 + ".onion";
    passInput.value = "";
    resultDisplay.textContent = "";
    modal.classList.add("active");
    passInput.focus();
  }

  function closeModal() {
    modal.classList.remove("active");
  }

  decryptBtn.addEventListener("click", async () => {
    const result = await decryptVault(passInput.value);
    resultDisplay.textContent = result + ".onion";
  });

  closeBtn.addEventListener("click", closeModal);
  modal.addEventListener("click", (e) => {
    if (e.target === modal) closeModal();
  });

  let progress = 0;
  document.addEventListener("keydown", (e) => {
    const expected = KONAMI_SEQUENCE[progress];
    const key = e.key.length === 1 ? e.key.toLowerCase() : e.key;
    if (key === expected) {
      progress++;
      if (progress === KONAMI_SEQUENCE.length) {
        progress = 0;
        openModal();
      }
    } else {
      progress = key === KONAMI_SEQUENCE[0] ? 1 : 0;
    }
  });
})();
